### ISSUE TITLE
Receive from NFC - in settings is not working

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-mobile#103]
![IMAGE 2024-03-11 07:39:17](https://github.com/lnflash/flash-mobile/assets/34528298/78dbaccc-c730-4e98-8aff-bc60205cb939)

**Comment by Nodirbek75** [comment]
@islandbitcoin Was it working before? I think it wasn't working before as well. 
When I debug it to find the issue, it wasn't working because **settlementAmount** was undefined.
I compared with Blink app and Blink doesn't have **Receive from NFC** button in settings screen. But there is in Receive screen. Should we move it to Receive screen as well?

**Comment by islandbitcoin** [comment]
> @islandbitcoin Was it working before? I think it wasn't working before as well. When I debug it to find the issue, it wasn't working because **settlementAmount** was undefined. I compared with Blink app and Blink doesn't have **Receive from NFC** button in settings screen. But there is in Receive screen. Should we move it to Receive screen as well?

yes, lets use the blink code, and move the NFC button to the receive screen. 

Do we need a backend change to populate the **settlementAmount**?

**Comment by Nodirbek75** [comment]
@

> > @islandbitcoin Was it working before? I think it wasn't working before as well. When I debug it to find the issue, it wasn't working because **settlementAmount** was undefined. I compared with Blink app and Blink doesn't have **Receive from NFC** button in settings screen. But there is in Receive screen. Should we move it to Receive screen as well?
> 
> yes, lets use the blink code, and move the NFC button to the receive screen.
> 
> Do we need a backend change to populate the **settlementAmount**?

No, we don't need a backend change. All front-end
