### ISSUE TITLE
Error when trying to Export transactions as CSV

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-mobile#105]
on Android, in the settings screen, when pressing the button "Export transactions as CSV, getting the error below"

` ERROR  [Error: com.lnflash: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts]`

It is working on iOS.

**Comment by Nodirbek75** [comment]
@islandbitcoin is it showing all the transactions correctly on IOS?
When I tried, it is not showing the transactions but showing the empty list.

[export-wallet.csv](https://github.com/lnflash/flash-mobile/files/14568907/export-wallet.csv)

**Comment by islandbitcoin** [comment]
no, its giving me an empty list too, but I didn't have any transactions when I was testing

**Comment by islandbitcoin** [comment]
Option has been hidden for now but let's leave this issue open so we can fix it.

**Comment by Nodirbek75** [comment]
@brh28 Can you look at this query when you have time. It is suppose to return transactions list to export but returning empty data.

`gql`
  query walletCSVTransactions($walletIds: [WalletId!]!) {
    me {
      id
      defaultAccount {
        id
        csvTransactions(walletIds: $walletIds)
      }
    }
  }
``

**Comment by brh28** [comment]
As expected, the query is not calling Ibex on the backend. Rather, this query internally calls the function [getTransactionsByWalletId](https://github.com/lnflash/flash/blob/main/src/services/ledger/index.ts#L105), which returns a type `LedgerTransaction`. This type is different from what's returned to the home page (`WalletTransaction`), which means we need to map the Ibex response to a `LedgerTransaction`. Hopefully I can get around to writing this this weekend.
