### ISSUE TITLE
No message on payment failure for NFC

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-mobile#118]
Edge case where if the NFC device does not have enough money, it will not pay the invoice. but Flash will not give any error message

Expected result: and alert saying that payment failed with the failure reason.

**Comment by islandbitcoin** [comment]
> Hi @islandbitcoin, if this had not been assigned to anyone, I'd like to work on it

Thanks! @Nodirbek75 can guide you if you have any questions about setting up or contributing.

**Comment by Nodirbek75** [comment]
@SiteBldrs let me know if you need any help for setting up and track the issue

**Comment by Nodirbek75** [comment]
@islandbitcoin when I tested, it is giving error message "Payment failed - Insufficient balance". Can you check this issue is resolved on your side as well and close the issue?

![Image](https://github.com/lnflash/flash-mobile/assets/57404324/7f207124-4b8c-4c59-8d45-7f58efa7518a)

**Comment by islandbitcoin** [comment]
I'm getting a "Failed to submit withdrawal request" error message.

**Comment by islandbitcoin** [comment]
![image](https://github.com/lnflash/flash-mobile/assets/34528298/2107dff4-fc1c-41a6-b4b8-43c0ff39a55f)
