### ISSUE TITLE
Transaction History is not showing up at the same time as the balance update

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-mobile#131]
Performance/Timing: The display and updating of the transaction history section on the Home Screen to update at the same time as the wallet balance.

**Comment by Nodirbek75** [comment]
@islandbitcoin You mean after sending or receiving the funds?
Or when app starts?

**Comment by Nodirbek75** [comment]
If you mean when app starts, balance showing cached balance, that's why transaction showing later after fetching it
