### ISSUE TITLE
Failure to send Lightning Address payment to internal users

### ISSUE THREAD

**Issue by brh28** [lnflash/flash-mobile#133]
Currently, we're able to send & receive to/from external wallets. However, when sending to another flashapp.me user, the UI is displaying the following error: 

<img src="https://github.com/lnflash/flash-mobile/assets/31115595/600c8df2-0e2b-46c1-bad1-2756281d98ae" alt="Description of your image" width="250" height="600">

This error is triggered in the `flash-mobile/app/screens/send-bitcoin-screen/send-bitcoin-details-screen.tsx` with the `lnurlInvoiceIncorrectDescription` message. Reading around the code, it appears we're successfully fetching an invoice from Ibex, but the client validation logic is failing. 

I'm unsure what the cause of the problem is - possible causes:

1. the response provided by the `/.well-known/lnurlp/<user>` endpoint is incorrect
2. Ibex's generated invoice is incorrect
3. LNURL request/responses are correct and the client-side check shouldn't be there

Sample invoice returned by Ibex includes the following fields:
```
"description": "",
"description_hash": "fa14d0a9c72d3c12274189edc4c092363ee160b62228480747c8d49c5461d85c",
```

**Comment by brh28** [comment]
To identify the cause of this problem, it would be nice to know what values are being compared at this condition: `if (paymentDetail.lnurlParams.metadataHash !== decodedDescriptionHash) {`

@Nodirbek75 Would you mind putting in some breakpoints or logs to get sample values at this line?

**Comment by Nodirbek75** [comment]
@brh28  Is this issue happening when sending to USD wallet of another flash user using lightening address?

**Comment by Nodirbek75** [comment]
I just created another flash account and sent from my original account to new account using USD wallet lightening address and it worked for me

**Comment by Nodirbek75** [comment]
@brh28 @islandbitcoin  Is this error still happening on your side?

**Comment by brh28** [comment]
Yes, i can leave more detailed reproduction steps, but it's occurring when sending to another flashapp users lightning address, such as `ben@staging.flashapp.me`

**Comment by Nodirbek75** [comment]
@brh28 It is trying to compare this values: 
`4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945` and `fa14d0a9c72d3c12274189edc4c092363ee160b62228480747c8d49c5461d85c`.

paymentDetail: 
`{"canGetFee": false, "canSendPayment": false, "canSetAmount": true, "canSetMemo": true, "convertMoneyAmount": [Function anonymous], "destination": "nick4@staging.flashapp.me", "destinationSpecifiedAmount": undefined, "lnurlParams": {"callback": "https://api-sandbox.poweredbyibex.io/lnurl/pay/invoice?k1=f760128d42aafbf9dc5a3473aa425845b4272a7a511e6ae0d22fc67824c3c34b", "commentAllowed": 140, "description": "", "domain": "api-sandbox.poweredbyibex.io", "fixed": false, "identifier": "", "image": "", "max": 100000, "metadata": [], "metadataHash": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945", "min": 1, "rawData": {"callback": "https://api-sandbox.poweredbyibex.io/lnurl/pay/invoice?k1=f760128d42aafbf9dc5a3473aa425845b4272a7a511e6ae0d22fc67824c3c34b", "commentAllowed": 140, "description": "Paying to LnUrl Pay", "domain": "api-sandbox.poweredbyibex.io", "identifier": "nick4@staging.flashapp.me", "image": "", "maxSendable": 100000000, "metadata": [Array], "minSendable": 1, "tag": "payRequest"}}, "memo": undefined, "paymentType": "lnurl", "sendingWalletDescriptor": {"currency": "BTC", "id": "e412ab4e-5b77-4657-a320-0024563910af"}, "setAmount": [Function setAmount], "setConvertMoneyAmount": [Function setConvertMoneyAmount], "setInvoice": [Function setInvoice], "setMemo": [Function setMemo], "setSendingWalletDescriptor": [Function setSendingWalletDescriptor], "settlementAmount": {"amount": 14, "currency": "BTC", "currencyCode": "BTC"}, "settlementAmountIsEstimated": false, "unitOfAccountAmount": {"amount": 1, "currency": "DisplayCurrency", "currencyCode": "USD"}}`

decodedInvoice:
`{"complete": true, "millisatoshis": "14000", "network": {"bech32": "bc", "pubKeyHash": 0, "scriptHash": 5, "validWitnessVersions": [0, 1]}, "payeeNodeKey": "02004d8933df4f002fa95d8c37ca43eb9c175d310aad55cc6d442e4accc3740029", "paymentRequest": "lnbc140n1pnqj75upp5vwmc0gggenmqnsaf76psnqvsrg2t8pvxtj2d7rxl5jgp4h45vkzshp5lg2dp2w8957pyf6p38kufsyjxclwzc9kyg5ysp68er2fc4rpmpwqcqzzsxqzuysp53ahawmdzlf5ghnp52ufaquhpsreav4cjvr5p0pj50hwva4ucpsuq9qyyssqku5z4zwn2jhl036n2wtrkmrftkkvrej0zn8xmqaqx7glxe3fclc5n78c8hn69eqqnztlrtlptjhl24xayer3wp9trk09e2q4gdmv70spyqfx00", "prefix": "lnbc140n", "recoveryFlag": 1, "satoshis": 14, "signature": "b7282a89d354aff7c75353963b6c695dacc1e64f14ce6d83a03791f36629c7f149f8f83de7a2e4009897f1afe15caff554dd26471704ab1d9e5ca8154376cf3e", "tags": [{"data": "63b787a108ccf609c3a9f6830981901a14b385865c94df0cdfa4901adeb46585", "tagName": "payment_hash"}, {"data": "fa14d0a9c72d3c12274189edc4c092363ee160b62228480747c8d49c5461d85c", "tagName": "purpose_commit_hash"}, {"data": 80, "tagName": "min_final_cltv_expiry"}, {"data": 900, "tagName": "expire_time"}, {"data": "8f6fd76da2fa688bcc345713d072e180f3d6571260e81786547ddcced7980c38", "tagName": "payment_secret"}, {"data": [Object], "tagName": "feature_bits"}], "timeExpireDate": 1711898144, "timeExpireDateString": "2024-03-31T15:15:44.000Z", "timestamp": 1711897244, "timestampString": "2024-03-31T15:00:44.000Z", "wordsTemp": "temp1pnqj75upp5vwmc0gggenmqnsaf76psnqvsrg2t8pvxtj2d7rxl5jgp4h45vkzshp5lg2dp2w8957pyf6p38kufsyjxclwzc9kyg5ysp68er2fc4rpmpwqcqzzsxqzuysp53ahawmdzlf5ghnp52ufaquhpsreav4cjvr5p0pj50hwva4ucpsuq9qyyssqku5z4zwn2jhl036n2wtrkmrftkkvrej0zn8xmqaqx7glxe3fclc5n78c8hn69eqqnztlrtlptjhl24xayer3wp9trk09e2q4gdmv70spd8k007"}`

**Comment by Nodirbek75** [comment]
It seems these hash values doesn't match, that's why giving error. 
But, when I comment out if statement, payment is going through successfully.

**Comment by brh28** [comment]
Thanks @Nodirbek75. I'll start looking into where these values are coming from and why they're being compared

**Comment by brh28** [comment]
Think I found the issue. See the PR description for details: https://github.com/lnflash/flash-pay/pull/11
