### ISSUE TITLE
First time user pressing start gets error, but then on second attempt it successfully creates wallet

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-mobile#149]
I've seen this problem before with low bandwidth internet access. 
Maybe we need to have a retry loop on the wallet creation before showing the error?
Also need to look into the rate limiting on firebase to make sure this isn't a problem when doing the retries

<img width="400" alt="Screenshot 2024-04-12 at 7 33 00 AM" src="https://github.com/lnflash/flash-mobile/assets/34528298/0ed96697-aa7b-4b17-aa05-6eceef58514b">

**Comment by Nodirbek75** [comment]
The issue:
When user press "Start" button as soon as they download the app and open it, it will triger `/auth/create/device-account` endpoint to create an account before fetching appCheckToken completed. 

Solution:
Add a loading indicator while fetching appCheckToken and disable start button
