### ISSUE TITLE
NFC payment fails when using BTC Wallet

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-mobile#160]
![9c02238ce899439609ba97e4d2034c8dfe0efeb55b26ac549a057815c33e6b1d](https://github.com/lnflash/flash-mobile/assets/34528298/27ce83f3-fc91-4af4-bfad-09483482d83f)

**Comment by Nodirbek75** [comment]
Error message: 
`{"data": {"reason": "Payment failed - Payment failed: CoreLightning method 'pay' failed with 'Destination 02cdd52e24f30bd308906172304b9b1afca1e7ea271a1ec21fdc57d3cbf0ba6285 is not reachable directly and all routehints were unusable.'."}, "type": "errorStatus"}`
