### ISSUE TITLE
enable mobile push notifications

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-mobile#172]
Currently working on the latest version of blink, should be able to enable it on flash also.

**Comment by Nodirbek75** [comment]
@islandbitcoin push notification is working on both android and ios for blink?

**Comment by Nodirbek75** [comment]
@brh28 Should we copy commits from blink repo to our repo or implement our own? Which one is better for you?

**Comment by Nodirbek75** [comment]
@brh28 And also, I may need your help to implement [Notification Delivery Service (NDS)](https://sdk-doc.breez.technology/notifications/setup_nds.html)  on the backend using [breez notify](https://github.com/breez/notify).

**Comment by Nodirbek75** [comment]
Notification types:

- [ ] Ibex USD Payment receive
- [ ] Breez BTC Payment receive
- [ ] Ibex USD Onchain confirm
- [ ] Breez BTC Onchain confirm
- [ ] Price change
- [ ] Marketing notification

**Comment by brh28** [comment]
2 issues I see on the backend so far:

1. Exception found in [Honeycomb trace](https://ui.honeycomb.io/island-bitcoin/environments/test/datasets/galoy-dev-websocket/result/rAZaLdZJSkk/trace/eWedpJm4trA?fields[]=s_name&fields[]=s_serviceName&source=events&span=ecf644b8f7d192b3)
```
UnknownNotificationsServiceError: Currency code is required with currency style.
    at handleCommonNotificationErrors (/app/lib/services/notifications/push-notifications.js:137:20)
    at lightningTxReceived (/app/lib/services/notifications/index.js:65:76)
    at /app/lib/services/tracing.js:335:35
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at AsyncLocalStorageContextManager.with (/app/node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
    at ContextAPI.with (/app/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
    at Tracer.startActiveSpan (/app/node_modules/@opentelemetry/sdk-trace-base/build/src/Tracer.js:122:32)
    at Object.lightningTxReceived (/app/lib/services/tracing.js:333:36)
    at /app/lib/services/ibex/webhook-server/routes/on-receive.js:37:70
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

2. Once we do figure this out, we'll need `GOOGLE_APPLICATION_CREDENTIALS` for notications to send.

**Comment by brh28** [comment]
PR to hopefully resolve the Currency code error mentioned above: https://github.com/lnflash/flash/pull/80

**Comment by brh28** [comment]
PR above has been merged and deployed.

Upon testing, notifcation did not get received but the logs seem to indicate it got triggered by our backend: https://ui.honeycomb.io/island-bitcoin/environments/test/datasets/test-ibex-webhook/result/JFYtswop8AE/trace/foU2QkhJyd7?fields[]=s_name&fields[]=s_serviceName&span=5df91fd27c5c8356

This could be resulting from me using graphene. @Nodirbek75 or @islandbitcoin if either of you could test on google Android and iOS, that would be appreciated

**Comment by islandbitcoin** [comment]
tested  on iOS, no notifications showing
tested on Android (GrapheneOS downloaded from PlayStore), no notifications showing

I tested on both staging and test environments

**Comment by brh28** [comment]
Deployed changes to fix currency amount in notification body (tested successfully) and update the firebase api call. Testing produces multiple notifications. The `ibex-webhook` shows the following logs:
```
{"level":30,"time":1723066820845,"pid":1,"hostname":"ibex-webhook-7fbc6cc545-hwcjx","module":"notifications","tokens":["fM32zYr8S0y4Ild1LnjVgS:APA91bGv0Q-r0nQHaQBAd7pNoGQS07Fj_HQzDqYWdIUiQlqHRwi0cHtAhIJdzvCG4yINVVD07dzcTJp2bfhaDXkARoUaO9gGfKIgGowzD4CjeTabjayNalv-FQnToxH3Mvr6bJ3YO_UD","crFblLFwR3elj6Ag7e4r_4:APA91bHePnyULjc0MIsFpK-LIE2ginLjo2ianDynxDbKYassUI-cp57Ob6UcVw-UGgMsw4VnkulpoPZkXXOHWyiz17gd5BOESfTn6e-cC2JrNs9xUbbBTBWc1Ws27FsYltYdKoAiu8VL"],"notification":{"title":"USD Transaction","body":"+$0.01"},"data":{"NotificationCategory":"Payments"}}
{"level":30,"time":1723066821256,"pid":1,"hostname":"ibex-webhook-7fbc6cc545-hwcjx","module":"notifications","response":{"responses":[{"success":false,"error":{"code":"messaging/registration-token-not-registered","message":"Requested entity was not found."}},{"success":true,"messageId":"projects/avid-ceiling-390418/messages/0:1723066821213317%5e8884415e888441"}],"successCount":1,"failureCount":1}}
/app/lib/services/ibex/webhook-server/routes/on-receive.js:52
    if (nsResp instanceof notifications_1.NotificationsService) {
               ^

TypeError: Function has non-object prototype 'undefined' in instanceof check
    at [Symbol.hasInstance] (<anonymous>)
    at /app/lib/services/ibex/webhook-server/routes/on-receive.js:52:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.16.0
```
And Honeycomb shows an [InvalidDeviceNotificationsServiceError](https://ui.honeycomb.io/island-bitcoin/environments/test/datasets/test-ibex-webhook/result/2gcWiGeugcR/trace/bwDH8aDJBEt?fields[]=s_name&fields[]=s_serviceName&span=b318713c45e6ef99)

Tested on Graphene Pixel 7a downloaded from play store

**Comment by islandbitcoin** [comment]
> Deployed changes to fix currency amount in notification body (tested successfully) and update the firebase api call. Testing produces multiple notifications. The `ibex-webhook` shows the following logs:
> 
> ```
> {"level":30,"time":1723066820845,"pid":1,"hostname":"ibex-webhook-7fbc6cc545-hwcjx","module":"notifications","tokens":["fM32zYr8S0y4Ild1LnjVgS:APA91bGv0Q-r0nQHaQBAd7pNoGQS07Fj_HQzDqYWdIUiQlqHRwi0cHtAhIJdzvCG4yINVVD07dzcTJp2bfhaDXkARoUaO9gGfKIgGowzD4CjeTabjayNalv-FQnToxH3Mvr6bJ3YO_UD","crFblLFwR3elj6Ag7e4r_4:APA91bHePnyULjc0MIsFpK-LIE2ginLjo2ianDynxDbKYassUI-cp57Ob6UcVw-UGgMsw4VnkulpoPZkXXOHWyiz17gd5BOESfTn6e-cC2JrNs9xUbbBTBWc1Ws27FsYltYdKoAiu8VL"],"notification":{"title":"USD Transaction","body":"+$0.01"},"data":{"NotificationCategory":"Payments"}}
> {"level":30,"time":1723066821256,"pid":1,"hostname":"ibex-webhook-7fbc6cc545-hwcjx","module":"notifications","response":{"responses":[{"success":false,"error":{"code":"messaging/registration-token-not-registered","message":"Requested entity was not found."}},{"success":true,"messageId":"projects/avid-ceiling-390418/messages/0:1723066821213317%5e8884415e888441"}],"successCount":1,"failureCount":1}}
> /app/lib/services/ibex/webhook-server/routes/on-receive.js:52
>     if (nsResp instanceof notifications_1.NotificationsService) {
>                ^
> 
> TypeError: Function has non-object prototype 'undefined' in instanceof check
>     at [Symbol.hasInstance] (<anonymous>)
>     at /app/lib/services/ibex/webhook-server/routes/on-receive.js:52:16
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> Node.js v20.16.0
> ```
> 
> And Honeycomb shows an [InvalidDeviceNotificationsServiceError](https://ui.honeycomb.io/island-bitcoin/environments/test/datasets/test-ibex-webhook/result/2gcWiGeugcR/trace/bwDH8aDJBEt?fields%5B%5D=s_name&fields%5B%5D=s_serviceName&span=b318713c45e6ef99)
> 
> Tested on Graphene Pixel 7a downloaded from play store

working for me too!

**Comment by islandbitcoin** [comment]
closing this issue unless anyone has objections

**Comment by islandbitcoin** [comment]
Notification Results:

I'm getting multiple notifications (3) when I pay to an invoice.
I'm getting zero notifications when I pay via LNURL/paycode/lightning address.

**Comment by brh28** [comment]
[PR](https://github.com/lnflash/flash/pull/83) to send notifications for lnurl payment receives. It also adds ibex-webhooks to the other send & receives, but currently only logs those requests

**Comment by brh28** [comment]
We've created the mechanism for push notifications. To my understanding, that is the purpose of this task. We haven't written code for all the notification types (e.g send/receive Lightning, send/receive onchain, send/receive Breex, marketing, etc). IMO each of these notification types should be split into their own issues so that we can prioritize accordingly. 

@islandbitcoin let me know if we want to close this out and create issues for the notification types, or if you want to leave this open with all notifications bundled into it.

**Comment by islandbitcoin** [comment]
closing as resolved
