### ISSUE TITLE
Improve send flow

### ISSUE THREAD

**Issue by Nodirbek75** [lnflash/flash-mobile#198]

**Comment by Nodirbek75** [comment]
![Image](https://github.com/user-attachments/assets/e627d754-c3e4-427f-bffc-3deb707b6814)
![Image](https://github.com/user-attachments/assets/6ee62360-e97f-47f0-a3a6-1692709991c8)

**Comment by Nodirbek75** [comment]
@islandbitcoin Updated above screen. Showing destination field if it is lnurl address or username and showing memo filed if it is editable.

**Comment by Nodirbek75** [comment]
@islandbitcoin What should be removed or edited in this screen?
![Screenshot_1722365561](https://github.com/user-attachments/assets/cf615ad9-3177-40fc-ab78-18cd88673542)

**Comment by islandbitcoin** [comment]
> @islandbitcoin What should be removed or edited in this screen? ![Screenshot_1722365561](https://private-user-images.githubusercontent.com/57404324/353580562-cf615ad9-3177-40fc-ab78-18cd88673542.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNjY1ODQsIm5iZiI6MTcyMjM2NjI4NCwicGF0aCI6Ii81NzQwNDMyNC8zNTM1ODA1NjItY2Y2MTVhZDktMzE3Ny00MGZjLWFiNzgtMThjZDg4NjczNTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE5MDQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxZWIwZWM4ZGQzZWU4Mjg4YmVhYzI0YmE5MjA2OWFhNTc1MTczNzk5Y2NjZWI5Mzc4YmE5NzhhM2Q3MTEwMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rvn9D6R5b06pKgWjeVMX6dBLMehItc9Ev8jdLfQPV9Q)

nothing
