### ISSUE TITLE
When using "import Wallet" the existing IBEX WalletId gets replaced, potentially losing user funds

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-mobile#199]
We need a solution to make sure we do not lose user funds when importing a new wallet.

**Comment by Nodirbek75** [comment]
One solution would be showing alert message to backup the current wallet or send the funds to importing wallet and show two buttons one navigates to backup screen, another navigates to send screen.

**Comment by brh28** [comment]
What is this "feature" for anyway? Unless there's a good reason for having it, I'd be in favor of hiding it from the UI

**Comment by islandbitcoin** [comment]
The use case is to import an existing wallet. (i.e. from an old phone)

If you downloaded Flash, and pressed start (instead of import wallet), but you still need to import your existing wallet from your old phone, this would be the user flow.

**Comment by islandbitcoin** [comment]
Ben and I discussed this, and I am in favor of hiding it in the UI until we come up with a proper solution.

**Comment by Nodirbek75** [comment]
> Ben and I discussed this, and I am in favor of hiding it in the UI until we come up with a proper solution.

You mean hiding it in the settings screen, right?
