### ISSUE TITLE
[NOSTR] Style the Chat Tab to match the light and dark color scheme of the rest of the App - Bounty #7

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-mobile#21]
The Chat tab is currently light purple, and I would like it to be white or black based on the light or dark theme of the app. 
This task is to change the color scheme of the screen, including background, header title, search bar, text color, etc. so that it looks like the contacts screen.

BOUNTY available ⚡⚡⚡

for testing the frontend you can connect the staging environment to http://api-development.flashapp.me:4002/graphql

**Comment by ecurrencyhodler** [comment]
Bounty has been [posted!](https://community.sphinx.chat/tickets?owner_id=021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b&created=1696548913)

**Comment by islandbitcoin** [comment]
Completed.
