### ISSUE TITLE
[NOSTR] Change the Chat Tab to display a default chat item in the chat tab list for each contact that is displayed in the contact list - Bounty #8

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-mobile#22]
This task to show a default list of chat items. 
This list should mimic the list of contacts on the contacts tab. The main difference is that on the chat tab, when the user clicks on the chat item, it will open a chat window where the user can chat to the contact using NOSTR encrypted direct messaging. 

Most of this code to list the contacts is present already, and there is WIP code using NIP-04 to send messages, please see [link](https://github.com/lnflash/flash-mobile/tree/main/app/screens/chat-screen). 

A more robust encryption standard (like NIP-44)  is much prefrerred, but the MVP may be sufficient with NIP-04. There is a supporting service https://github.com/GaloyMoney/galoy-nostr that can be forked to include a messaging module in the /src folder if that makes more sense. A successful PR will be a working version able to send and receive messages to other nostr users.

**Comment by ecurrencyhodler** [comment]
Bounty has been [posted](https://community.sphinx.chat/tickets?owner_id=021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b&created=1696549493).

**Comment by islandbitcoin** [comment]
This issue is no longer applicable, as we will probably be using the nostr directory as the flash contact list.
