### ISSUE TITLE
[NOSTR]  Add a notification badge overlaying the chat Tab icon at the bottom of the screen - Bounty #10

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-mobile#24]
This task is to add a notification badge to the Chat Tab icon.

When a message is received from any other user (excluding the support public chat) the user will be alerted by seeing the number of messages in a badge near the top right corner of the chat tab icon. If the same contact messages multiple times, that should still only count as 1 increment on the message badge. So if 3 different contacts have messaged the user, the user should see a badge with the number 3 on it.

BOUNTY available ⚡⚡⚡

for testing the frontend you can connect the staging environment to http://api-development.flashapp.me:4002/graphql

**Comment by ecurrencyhodler** [comment]
Bounty has been [posted](https://community.sphinx.chat/tickets?owner_id=021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b&created=1696549671)!

**Comment by VividhPandey003** [comment]
Hey if you don't mind could you please tell me the skill requirement for it. I want to know this iff I'll be able to do this or not

**Comment by islandbitcoin** [comment]
> Hey if you don't mind could you please tell me the skill requirement for it. I want to know this iff I'll be able to do this or not

- react-native
- typescript
- NOSTR experience
- chat app development experience

**Comment by wright-eric** [comment]
Hi @ecurrencyhodler  @islandbitcoin  is this still up for grab?

**Comment by islandbitcoin** [comment]
closing this issue and rolling the task up to https://github.com/lnflash/flash-mobile/pull/102
