### ISSUE TITLE
Update transaction limits screen

### ISSUE THREAD

**Issue by Nodirbek75** [lnflash/flash-mobile#245]
- remove the stablesats limits
- add an information section explaining the USD denomination and will change based on exchange rates
![Screenshot_2024-09-02_at_12 45 14_PM](https://github.com/user-attachments/assets/bafd7865-914f-46e5-abfd-a89a45157614)

**Comment by Nodirbek75** [comment]
@islandbitcoin removed the stablesats limits.

![Simulator Screenshot - iPhone 11 Pro Max - 2024-09-09 at 13 27 52](https://github.com/user-attachments/assets/251caa3e-d52f-4963-b74c-9432494d4711)

**Comment by Nodirbek75** [comment]
@islandbitcoin Can you let me know the text for "an information section explaining the USD denomination and will change based on exchange rates". So, I'll add that too

**Comment by Nodirbek75** [comment]
![Simulator Screenshot - iPhone 11 Pro Max - 2024-09-10 at 11 21 17](https://github.com/user-attachments/assets/920fe49c-38b6-44a5-a53c-b9de21cb7f00)

**Comment by islandbitcoin** [comment]
looks good!
