### ISSUE TITLE
[NOSTR] Configure NOSTR node for support channel and website chat widget - Bounty #11

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-mobile#25]
This task is to update the currently running NOSTREAM node on Digital Ocean to be labeled and optimized to be a prioritized relay for the Flash Support Public Chat. All other users wanting to connect to this relay should have to pay a one-time lightning invoice of 8760 sats. 

Contact me for temporary access to the DO Droplet via SSH to modify the relay

Here is the relay: https://nostr.watch/relay/nostr.pleb.network

BOUNTY available ⚡⚡⚡

for testing the frontend you can connect the staging environment to http://development.flashapp.me:4002/graphql

**Comment by ecurrencyhodler** [comment]
Bounty has been [posted](https://community.sphinx.chat/tickets?owner_id=021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b&created=1696550076)!

**Comment by 1440000bytes** [comment]
I can work on this issue.

> Contact me for temporary access to the DO Droplet via SSH to modify the relay

You can DM me the SSH credentials on telegram or send email to alicexbt@protonmail.com

> for testing the frontend you can connect the staging environment to http://api-development.flashapp.me:4002/graphql

This link is not working

**Comment by islandbitcoin** [comment]
I made an update to the server URL - http://development.flashapp.me:4002/graphql

**Comment by 1440000bytes** [comment]
Code for nostr relay that requires one time registration using LN except whitelisted pubkeys: https://github.com/1440000bytes/relayer/tree/master/examples/expensive-whitelist

Steps to setup this nostr relay:

1. Run [Bitcoin Core](https://bitcoincore.org/en/download/). Use `signet` for testing initially.
2. Run [CLN](https://github.com/ElementsProject/lightning) using this command: `lightningd --network=signet --log-level=debug`
3. Connect to a peer using this command: `lightning-connect 02dfb81e2f7a3c4c9e8a51b70ef82b4a24549cc2fab1f5b2fd636501774a918991@103.99.171.201:39735`
4. Install postgres and run nostr relay
