### ISSUE TITLE
Warning modal pops up every time I send funds to a Flash username on the send destination screen.

### ISSUE THREAD

**Issue by Nodirbek75** [lnflash/flash-mobile#257]
<img width="414" alt="Screenshot_2024-09-13_at_6 26 46_PM" src="https://github.com/user-attachments/assets/de079da7-6298-4c64-a2cf-121badbec85e">

**Comment by Nodirbek75** [comment]
The sendBitcoinDestination query is being called to fetch contacts of users I've sent funds to before, but the contacts field is always empty after sending to another Flash user. @brh28 , can you check if the recipient is being added to the contacts list after I send funds to another user?

![Screenshot 2024-09-16 at 3 10 24 PM](https://github.com/user-attachments/assets/ff5ca7dd-085d-44bd-a300-cae1e4781024)

**Comment by islandbitcoin** [comment]
I'm seeing the contacts in mongoDB once a pay to a username. 

<img width="574" alt="Screenshot 2024-09-16 at 11 10 57 AM" src="https://github.com/user-attachments/assets/872cd69c-4e16-4008-a9f0-4a4cc264a0e6">

**Comment by islandbitcoin** [comment]
in test I can see this query, but it has a 'deprecated' annotation on it:

<img width="1506" alt="Screenshot 2024-09-16 at 12 19 11 PM" src="https://github.com/user-attachments/assets/3bd39440-2b98-489a-a157-1171665b8f62">

**Comment by brh28** [comment]
Hey @Nodirbek75, my guess is contacts aren't being added during the payment flow, but when I tested the `IntraLedgerUsdPaymentSend` mutation locally I did not see an error. Could you provide the following info:

1. Who are the users you're testing to and from?
2. Which environment are you testing in?
3. What is the graphql mutation that is triggered by this payment flow?

**Comment by Nodirbek75** [comment]
> Hey @Nodirbek75, my guess is contacts aren't being added during the payment flow, but when I tested the `IntraLedgerUsdPaymentSend` mutation locally I did not see an error. Could you provide the following info:
> 
> 1. Who are the users you're testing to and from?
> 2. Which environment are you testing in?
> 3. What is the graphql mutation that is triggered by this payment flow?

1. Flash users
2. Test instance
3. intraLedgerUsdPaymentSend mutation is being used

**Comment by Nodirbek75** [comment]
@brh28 if contacts aren't being added during the payment flow, I think need to check if `IntraLedgerUsdPaymentSend` mutation has a logic to add a username to contacts list

**Comment by brh28** [comment]
Still unable to reproduce this issue when following  these steps:
1. I created a new user in the test environment ('ben4')
2. I sent a small payment to user 'nick'
3. Verified contacts were added to both 'ben4' and 'nick'
4. Queried "contacts":
```
query me {
    me {
        contacts {
            id
            username
            alias
            transactionsCount
        }
    }
}
```
and got back:
```
{
    "data": {
        "me": {
            "contacts": [
                {
                    "id": "nick",
                    "username": "nick",
                    "alias": "nick",
                    "transactionsCount": 1
                }
            ]
        }
    }
}
```
