### ISSUE TITLE
[NOSTR] Ability to add a contact to chat tab using NPUB or NOSTR HEX PUBKEY or NIP-05 username - Bounty #12

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-mobile#26]
This task is to give users the ability to add a contact to chat tab using NPUB or nostr hex PUBKEY or NIP-05 username. When any one of these are typed into the search bar on the chat tab, an automatic search should be done on the NOSTR relay (and other relays known for collecting type 0 events such as wss://purplepag.es) and return a list (fuzzy logic) matching the search.

When a contact from the search result list is selected, a direct message chat screen should open with that contact.

If the user closes the window without sending a message, then no chat item is saved to the list of chats. 

If the user sends a message to the contact, then the contact is added to the users list of contacts in the chat tab. 
The lightning address should be used as an identifier if it is available on the NOSTR profile.

**Comment by ecurrencyhodler** [comment]
Bounty has been[ posted!](https://community.sphinx.chat/tickets?owner_id=021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b&created=1696706374)

**Comment by Nightrider0098** [comment]
@ecurrencyhodler Can i pick this up?

**Comment by islandbitcoin** [comment]
> @ecurrencyhodler Can i pick this up?

@Nightrider0098 no, sorry, I've closed the bounty since we are working on the nostr solution using a more holistic approach, but you are very welcome to contribute! Here is the current active PR being worked on

https://github.com/lnflash/flash-mobile/pull/102

**Comment by islandbitcoin** [comment]
closing this issue and rolling the task up into https://github.com/lnflash/flash-mobile/pull/102
