### ISSUE TITLE
[IBEX] Complete IBEX integration with galoy backend using USD wallet to send lightning via LNURL - Bounty #6

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-mobile#28]
This task is to replace the galoy USD (stablesats) wallet with the IBEX custodial USD wallet when paying to a LNURL.

The LNURL QR code is generated from the well-known folder on the domain name being used as the hostname, along with the username of the receiver. 

Code improvements and suggestions are welcome.

For testing the frontend you can connect the staging environment to http://api-development.flashapp.me:4002/graphql
For testing the IBEX API you can connect to http://api-development.flashapp.me:8760/api/v1/

BOUNTY available ⚡⚡⚡

**Comment by ecurrencyhodler** [comment]
Bounty [posted!](https://community.sphinx.chat/tickets?owner_id=021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b&created=1696812446)

**Comment by islandbitcoin** [comment]
Completed on https://github.com/lnflash/flash-mobile/pull/29
