### ISSUE TITLE
Change Default Theme to "Light Mode"

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-mobile#283]

**Comment by Nodirbek75** [comment]
@brh28 I think the default theme is being set to 'system' on the backend when a user is created. Can you change it to 'light'?

**Comment by brh28** [comment]
> @brh28 I think the default theme is being set to 'system' on the backend when a user is created. Can you change it to 'light'?

How is it being set? Is there a query & mutation you're seeing in the graphql api?
