### ISSUE TITLE
Cannot send to username with foreign characters (i.e. é)

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-mobile#292]
![Simulator Screenshot - iPhone 15 Pro - 2024-10-26 at 11 34 45](https://github.com/user-attachments/assets/cac1e7b4-4ba5-4487-bb39-7266a83a0f24)

**Comment by Nodirbek75** [comment]
@islandbitcoin The `@galoymoney/client` package is being used to validate destinations. When I send a username with foreign characters, I'm getting this response: `{"paymentType": "unknown", "valid": false}`."

**Comment by islandbitcoin** [comment]
so how do we fix that?

**Comment by Nodirbek75** [comment]
> so how do we fix that?

We should fork galoymoney/client project and modify it for our needs. But, I'm not sure if network supports foreign characters.
