### ISSUE TITLE
Implement error log reporting to Breez SDK for all methods

### ISSUE THREAD

**Issue by Nodirbek75** [lnflash/flash-mobile#54]

**Comment by islandbitcoin** [comment]
@Nodirbek75 Is this complete? I think Breez is getting reporting now...

**Comment by Nodirbek75** [comment]
> @Nodirbek75 Is this complete? I think Breez is getting reporting now...

When I checked last time reporting was added already in breez-sdk index.ts file

**Comment by islandbitcoin** [comment]
closing as completed with [Liquid PR](https://github.com/lnflash/flash-mobile/pull/248)
