### ISSUE TITLE
Modify Settings to have all flash links instread of Blink links (Contact Us, Join the Community, Rate us on Store)

### ISSUE THREAD

**Issue by Nodirbek75** [lnflash/flash-mobile#55]
- [x] hide mattermost
- [x] change the link of telegram
- [x] change the link of status page or hide it
- [ ] change the link of whatsApp  or hide it
- [x] hide "Rate us on App Store" button

**Comment by islandbitcoin** [comment]
Definitely need to take my personal WhatsApp number off of this lol

**Comment by islandbitcoin** [comment]
Hide Mattermost

**Comment by Nodirbek75** [comment]
@islandbitcoin Can you provide the links of telegram, whatsApp if exist, status page?
