### ISSUE TITLE
[NOSTR] Each user should be able to open a new chat window with other flash users by searching for their npub, or their lightning address.

### ISSUE THREAD

**Issue by Nodirbek75** [lnflash/flash-mobile#63]

**Comment by abhay-raizada** [comment]
The steps to do this would require:

1. Search with npub: Load user kind0s on npubsearch, currently looks like this: 
<img width="470" alt="image" src="https://github.com/lnflash/flash-mobile/assets/8532031/3e0b40df-6d94-4ade-8798-62897a36bede">
2.  Onclick: User should be able to open a new chat window (currently looks like this): 
<img width="389" alt="image" src="https://github.com/lnflash/flash-mobile/assets/8532031/d7ad5399-e4e0-4ce4-8e40-853de02b71da">
3. User Should be able to view past chats and be able to send & receive messages. 
3. Improve Chat designs
4. Make sure it works with other flash users.

I'm planning to make small PRs for each of the sub-items

**Comment by abhay-raizada** [comment]
This should be tracked with https://github.com/lnflash/flash-mobile/issues/100 itself for NIP17, already done for nip04
