### ISSUE TITLE
Hide estimated fee for breez sdk and show note for users

### ISSUE THREAD

**Issue by Nodirbek75** [lnflash/flash-mobile#77]

**Comment by islandbitcoin** [comment]
The BreezSDK does not give a method for calculating lightning fees before sending a transaction. Two things for this issue to be completed:

1) Hide the component that displays the fee ONLY when we are sending from the BTC Wallet (show the component when sending from the USD Wallet)
2) Give the user a label that lets them know there MAY be a small fee for routing.
