### ISSUE TITLE
Better Error handling on start flow

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-mobile#92]
When the start button is pressed, if the server cannot be reached there are no messages or alerts being given to the user. 

The app should have a graceful message to let the user know that the server is offline, and should open the app in "explore wallet" mode instead.

**Comment by Nodirbek75** [comment]
@islandbitcoin  Should I put this modal from original design and remove Register phone account?
![Screenshot_1708348328](https://github.com/lnflash/flash-mobile/assets/57404324/799f7c68-fed4-4589-bf34-2ce5a376a866)

**Comment by islandbitcoin** [comment]
yes, and change the wording from "Trial account creation failed" to "Account creation temporarily unavailable".

And remove the word trial from the text
