### ISSUE TITLE
[BUG] BTC wallet funds disappear when Breez channel closes 

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash-mobile#97]
Sometimes on a Breez-SDK node, the channel might be closed for many reasons. lack of use, force closes, etc.
when this happens, the funds are held in a pending UTXO that needs to be claimed/swept to the users on-chain address. 

Flash-mobile needs a function that can detect when a channel closes, and sweep the funds to the users on-chain address.

**Comment by Nodirbek75** [comment]
@islandbitcoin is it happening when user delete the account?

**Comment by islandbitcoin** [comment]
No, it only happens when a channel is closed by the LSP

**Comment by Nodirbek75** [comment]
Is there a way to detect if a channel is closed or going to close?

**Comment by islandbitcoin** [comment]
you can run a method to see if there are pending swap funds from a closed channel:
https://sdk-doc.breez.technology/guide/send_onchain.html?highlight=pending#list-in-progress-swaps

then you can redeem the funds:
https://sdk-doc.breez.technology/guide/closed_channels.html

**Comment by Don2kay905** [comment]
> @islandbitcoin is it happening when user delete the account?

 M1F
